# Generated by Django 5.2.4 on 2025-09-05 02:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('direccion', models.CharField(max_length=300)),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('horario_apertura', models.TimeField()),
                ('horario_cierre', models.TimeField()),
                ('dias_apertura', models.CharField(default='Lunes a Domingo', max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cafeterias/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_calificaciones', models.PositiveIntegerField(default=0)),
                ('total_me_gusta', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('duracion_estimada', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('distancia_total', models.DecimalField(decimal_places=2, help_text='Distancia en kilómetros', max_digits=8)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('calificacion', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cafeteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cafeteria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('edad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecorridoCafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('cafeteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cafeteria')),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recorrido')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('recorrido', 'cafeteria')},
            },
        ),
        migrations.AddField(
            model_name='recorrido',
            name='cafeterias',
            field=models.ManyToManyField(through='core.RecorridoCafeteria', to='core.cafeteria'),
        ),
        migrations.CreateModel(
            name='RecorridoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('E', 'En Progreso'), ('C', 'Completado'), ('A', 'Abandonado')], default='P', max_length=1)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('cafeterias_visitadas', models.ManyToManyField(blank=True, to='core.cafeteria')),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recorrido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeGusta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cafeteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cafeteria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'cafeteria')},
            },
        ),
        migrations.CreateModel(
            name='CafeteriaTipoCafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('cafeteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cafeteria')),
                ('tipo_cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipocafe')),
            ],
            options={
                'unique_together': {('cafeteria', 'tipo_cafe')},
            },
        ),
    ]
