# Generated by Django 5.2.4 on 2025-09-26 04:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafeteria',
            name='dias_apertura',
        ),
        migrations.RemoveField(
            model_name='cafeteria',
            name='horario_apertura',
        ),
        migrations.RemoveField(
            model_name='cafeteria',
            name='horario_cierre',
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='estacionamiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='horario',
            field=models.CharField(default='L-D: 8:00-20:00', max_length=100),
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='precio_promedio',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='terraza',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='wifi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='zona',
            field=models.CharField(default='Centro', max_length=50),
        ),
        migrations.AddField(
            model_name='recorrido',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recorrido',
            name='dificultad',
            field=models.CharField(default='Fácil', max_length=50),
        ),
        migrations.AddField(
            model_name='recorrido',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='recorrido',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recorridos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipocafe',
            name='intensidad',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='tipocafe',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=8),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponible', models.BooleanField(default=True)),
                ('popular', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cafeteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.cafeteria')),
                ('tipo_cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipocafe')),
            ],
            options={
                'unique_together': {('cafeteria', 'nombre')},
            },
        ),
    ]
