# Generated by Django 5.2.4 on 2025-09-29 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_cafeteria_dias_apertura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioCafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_apertura', models.TimeField(blank=True, null=True)),
                ('hora_cierre', models.TimeField(blank=True, null=True)),
                ('cerrado', models.BooleanField(default=False)),
                ('cafeteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_detallados', to='core.cafeteria')),
            ],
            options={
                'ordering': ['dia_semana'],
                'unique_together': {('cafeteria', 'dia_semana')},
            },
        ),
    ]
