# Generated by Django 5.2.4 on 2025-09-29 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_producto_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuenoCafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('direccion_personal', models.CharField(max_length=300)),
                ('nombre_cafeteria', models.CharField(max_length=200)),
                ('descripcion_cafeteria', models.TextField()),
                ('direccion_cafeteria', models.CharField(max_length=300)),
                ('telefono_cafeteria', models.CharField(max_length=20)),
                ('horario_atencion', models.CharField(default='L-D: 8:00-20:00', max_length=100)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('wifi', models.BooleanField(default=True)),
                ('terraza', models.BooleanField(default=False)),
                ('estacionamiento', models.BooleanField(default=False)),
                ('zona', models.CharField(default='Centro', max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('comentarios_admin', models.TextField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('cafeteria', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cafeteria')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
